// GENERATED — do not edit this file by hand.
// Written by `cargo run --locked -p ea-ui-contracts --bin emit-ts`.
// Every literal below has exactly one source, and that source is Rust.

// The closed unions of the contract surface.

export type SyncStatus =
  | 'lokal gesichert'
  | 'Upload ausstehend'
  | 'synchronisiert'
  | 'Fehler'

export type DetailCause =
  | 'Netzarchiv wartet'
  | 'Queuegrenze erreicht'
  | 'Profil nicht freigegeben'
  | 'Wiederaufnahme erschoepft'

export type QuarantineReason =
  | 'malformed'
  | 'duplicate'
  | 'conflicting'
  | 'unattributable'

export type LocalAuditOutcomeV1 =
  | 'Failed'
  | 'Accepted'
  | 'Completed'

export type KeyProtectionProfileV1 =
  | 'OsWrapped'
  | 'HardwareNonExportable'
  | 'OfflineEncryptedContainer'
  | 'Pkcs11'
  | 'ServerSecretStoreOrHsm'

export type OperatorRoleV1 =
  | 'Writer'
  | 'Reader'
  | 'OrganizationAdmin'

export type SignerRole =
  | 'Writer'
  | 'Reader'
  | 'OrganizationAdmin'
  | 'Root'
  | 'KeyApprover'
  | 'HistoricalGrantAuthority'
  | 'ServerReceipt'
  | 'DeletionAttest'
  | 'RecoveryRecipient'

export type FinalizationPhase =
  | 'ReversibleDraft'
  | 'PreparedAndFlushed'
  | 'DraftKeyAbsent'
  | 'GrantsPublished'
  | 'EntryCommitted'
  | 'NetworkArchivePublished'
  | 'Reconciled'

// The Writer view models.

export type SyncStateView = {
  readonly status: SyncStatus
  readonly detailCause: DetailCause | null
}

export type FinalizationPreviewView = {
  readonly proposedSequence: number
  readonly bindsPredecessor: boolean
  readonly effectiveNow: number
  readonly trustAgeMs: number
  readonly readerTrustRefreshMs: number
  readonly trustRefreshOverdue: boolean
  readonly hardBlock: boolean
}

export type FinalizeOutcomeView = {
  readonly sequence: number
  readonly sync: SyncStateView
}

export type ArchiveHealthSummaryView = {
  readonly healthy: boolean
  readonly findingCodes: readonly string[]
  readonly quarantineReasons: readonly QuarantineReason[]
}

export type PostureRequirementView = {
  readonly requirementCode: string
  readonly satisfied: boolean | null
  readonly evidenceCode: string
}

export type DevicePostureSummaryView = {
  readonly requirements: readonly PostureRequirementView[]
  readonly productionReady: boolean
}

export type PendingFinalizationResumeView = {
  readonly phase: FinalizationPhase
  readonly irreversible: boolean
  readonly outcomeCode: string | null
  readonly outcomeSequence: number | null
}

export type IncidentIdentityView = {
  readonly localCivilYear: number
  readonly incidentNumber: string
}

// The value arrays, so that no consumer repeats a literal.

export const SYNC_STATUS_VALUES = [
  'lokal gesichert',
  'Upload ausstehend',
  'synchronisiert',
  'Fehler',
] as const

export const DETAIL_CAUSE_VALUES = [
  'Netzarchiv wartet',
  'Queuegrenze erreicht',
  'Profil nicht freigegeben',
  'Wiederaufnahme erschoepft',
] as const

export const QUARANTINE_REASON_VALUES = [
  'malformed',
  'duplicate',
  'conflicting',
  'unattributable',
] as const

export const LOCAL_AUDIT_OUTCOME_V1_VALUES = [
  'Failed',
  'Accepted',
  'Completed',
] as const

export const KEY_PROTECTION_PROFILE_V1_VALUES = [
  'OsWrapped',
  'HardwareNonExportable',
  'OfflineEncryptedContainer',
  'Pkcs11',
  'ServerSecretStoreOrHsm',
] as const

export const OPERATOR_ROLE_V1_VALUES = [
  'Writer',
  'Reader',
  'OrganizationAdmin',
] as const

export const SIGNER_ROLE_VALUES = [
  'Writer',
  'Reader',
  'OrganizationAdmin',
  'Root',
  'KeyApprover',
  'HistoricalGrantAuthority',
  'ServerReceipt',
  'DeletionAttest',
  'RecoveryRecipient',
] as const

export const FINALIZATION_PHASE_VALUES = [
  'ReversibleDraft',
  'PreparedAndFlushed',
  'DraftKeyAbsent',
  'GrantsPublished',
  'EntryCommitted',
  'NetworkArchivePublished',
  'Reconciled',
] as const
