// GENERATED — do not edit this file by hand.
// Written by `cargo run --locked -p ea-ui-contracts --bin emit-ts`.
// Every literal below has exactly one source, and that source is Rust.

// The closed unions of the contract surface.

export type SyncStatus =
  | 'lokal gesichert'
  | 'Upload ausstehend'
  | 'synchronisiert'
  | 'Fehler'

export type DetailCause =
  | 'Netzarchiv wartet'
  | 'Queuegrenze erreicht'
  | 'Profil nicht freigegeben'
  | 'Wiederaufnahme erschoepft'

export type QuarantineReason =
  | 'malformed'
  | 'duplicate'
  | 'conflicting'
  | 'unattributable'

export type LocalAuditOutcomeV1 =
  | 'Failed'
  | 'Accepted'
  | 'Completed'

export type KeyProtectionProfileV1 =
  | 'OsWrapped'
  | 'HardwareNonExportable'
  | 'OfflineEncryptedContainer'
  | 'Pkcs11'
  | 'ServerSecretStoreOrHsm'

export type OperatorRoleV1 =
  | 'Writer'
  | 'Reader'
  | 'OrganizationAdmin'

export type SignerRole =
  | 'Writer'
  | 'Reader'
  | 'OrganizationAdmin'
  | 'Root'
  | 'KeyApprover'
  | 'HistoricalGrantAuthority'
  | 'ServerReceipt'
  | 'DeletionAttest'
  | 'RecoveryRecipient'

export type FinalizationPhase =
  | 'ReversibleDraft'
  | 'PreparedAndFlushed'
  | 'DraftKeyAbsent'
  | 'GrantsPublished'
  | 'EntryCommitted'
  | 'NetworkArchivePublished'
  | 'Reconciled'

export type StaleDecision =
  | 'Fresh'
  | 'StaleAcknowledgeable'
  | 'HardBlock'

export type HealthFinding =
  | 'EA-ARCHIVE-HEALTH-MISSING-FILE'
  | 'EA-ARCHIVE-HEALTH-MODIFIED-FILE'
  | 'EA-ARCHIVE-HEALTH-HASH-SIGNATURE-CHAIN'
  | 'EA-ARCHIVE-HEALTH-MISSING-GRANT'
  | 'EA-ARCHIVE-HEALTH-UNAUTHORIZED-STUB'
  | 'EA-ARCHIVE-HEALTH-INCOMPLETE-TRUST'
  | 'EA-ARCHIVE-HEALTH-ORPHAN-OR-TEMPORARY'
  | 'EA-ARCHIVE-HEALTH-SEQUENCE-FORK-ROLLBACK'
  | 'EA-ARCHIVE-HEALTH-FREE-SPACE'
  | 'EA-ARCHIVE-HEALTH-FILESYSTEM-SEMANTICS'

export type PatientCountStatus =
  | 'Unknown'
  | 'Known'

export type LocalWriterLockDiagnosis =
  | 'Missing'
  | 'AbandonedInert'
  | 'LiveOwner'
  | 'Unreadable'

export type DestructionStateV1 =
  | 'requested'
  | 'inProgress'
  | 'pendingBackupExpiry'
  | 'completeManagedScope'
  | 'incompleteUnreachableReplica'

export type GoLiveRequirementStatus =
  | 'Confirmed'
  | 'NotMet'
  | 'NotAutomaticallyVerifiable'

export type TrustCeremonyKind =
  | 'DeviceApprove'
  | 'DeviceRevoke'
  | 'PolicyChange'
  | 'WriterTransition'

export type TrustCeremonyStep =
  | 'PendingRequest'
  | 'FingerprintConfirmed'
  | 'AdminAuthorized'
  | 'RootRequestExported'
  | 'RootReplyImported'
  | 'RegistryPublished'
  | 'TargetPublished'

export type FingerprintSubjectV1 =
  | 'RegistrationRequest'
  | 'IssuedCertificate'

export type TrustCeremonyRoundV1 =
  | 'IssueTarget'
  | 'ActivateRegistry'

export type WriterTransitionPhase =
  | 'NoTransition'
  | 'Prepared'
  | 'Activated'

export type ClockReleaseAvailability =
  | 'Offered'
  | 'IndependentTimeUnavailable'
  | 'NotBlocked'

export type RevocationTargetClass =
  | 'NonAdminDevice'
  | 'OperatorBinding'
  | 'Component'

export type ClockReleaseJustificationV1 =
  | 'OperatorVerifiedWallClock'
  | 'PlatformTimeSourceRecovery'
  | 'HardwareClockMaintenance'

// The Writer view models.

export type SyncStateView = {
  readonly status: SyncStatus
  readonly detailCause: DetailCause | null
}

export type FinalizationPreviewView = {
  readonly proposedSequence: number
  readonly bindsPredecessor: boolean
  readonly effectiveNow: number
  readonly trustAgeMs: number
  readonly readerTrustRefreshMs: number
  readonly trustRefreshOverdue: boolean
  readonly staleDecision: StaleDecision
}

export type FinalizeOutcomeView = {
  readonly sequence: number
  readonly entryHash: string
  readonly objectHash: string
  readonly sync: SyncStateView
}

export type ArchiveHealthSummaryView = {
  readonly healthy: boolean
  readonly findingCodes: readonly HealthFinding[]
  readonly quarantineReasons: readonly QuarantineReason[]
}

export type PostureRequirementView = {
  readonly requirementCode: string
  readonly satisfied: boolean | null
  readonly evidenceCode: string
}

export type DevicePostureSummaryView = {
  readonly requirements: readonly PostureRequirementView[]
  readonly productionReady: boolean
}

export type PendingFinalizationResumeView = {
  readonly phase: FinalizationPhase
  readonly irreversible: boolean
  readonly outcomeCode: string | null
  readonly outcomeSequence: number | null
}

export type IncidentIdentityView = {
  readonly localCivilYear: number
  readonly incidentNumber: string
}

export type CoordinatesView = {
  readonly latE7: number
  readonly lonE7: number
}

export type OccurredAtView = {
  readonly start: number
  readonly end: number | null
}

export type KeywordView = {
  readonly referenceId: string | null
  readonly displayText: string
}

export type StructuredAddressView = {
  readonly street: string | null
  readonly houseNumber: string | null
  readonly postalCode: string | null
  readonly locality: string | null
  readonly adminArea: string | null
  readonly countryCode: string | null
}

export type LocationView = {
  readonly freeText: string | null
  readonly address: StructuredAddressView | null
  readonly coordinates: CoordinatesView | null
}

export type PersonnelSelectionView = {
  readonly masterPersonnelId: string | null
  readonly displayName: string
  readonly roleLabel: string | null
}

export type VehicleSelectionView = {
  readonly masterVehicleId: string | null
  readonly displayName: string
  readonly radioCallName: string | null
  readonly licensePlate: string | null
}

export type ExternalOrganizationView = {
  readonly id: string | null
  readonly displayName: string
}

export type IncidentInputView = {
  readonly humanIncidentNumber: string
  readonly occurredAt: OccurredAtView
  readonly keyword: KeywordView
  readonly location: LocationView
  readonly personnel: readonly PersonnelSelectionView[]
  readonly personnelEmptyReason: string | null
  readonly vehicles: readonly VehicleSelectionView[]
  readonly vehiclesEmptyReason: string | null
  readonly patientCountStatus: PatientCountStatus
  readonly patientCount: number | null
  readonly notes: string | null
  readonly externalOrganizations: readonly ExternalOrganizationView[]
}

export type CorrectionReferenceView = {
  readonly originalRecordId: string
  readonly originalEntryHash: string
  readonly originalSequence: number
}

export type AmendmentChangeView = {
  readonly fieldPath: string
  readonly changeText: string
}

export type AmendmentInputView = {
  readonly reference: CorrectionReferenceView
  readonly reason: string
  readonly changes: readonly AmendmentChangeView[]
}

export type DraftStateView = {
  readonly incident: IncidentInputView
  readonly amendment?: AmendmentInputView | null
  readonly sync: SyncStateView
}

export type MasterDataResultView = {
  readonly personnel: readonly PersonnelSelectionView[]
  readonly vehicles: readonly VehicleSelectionView[]
  readonly personnelTotal: number
  readonly vehicleTotal: number
}

export type StaleAcknowledgementView = {
  readonly captured: boolean
  readonly proofCode: string
}

export type ReauthResultView = {
  readonly fresh: boolean
  readonly purposeCode: string
}

export type DiscardStateView = {
  readonly phaseCode: string
  readonly complete: boolean
}

export type BundleExportView = {
  readonly path: string
  readonly objectCount: number
  readonly byteCount: number
}

export type PendingResumeOutcomeView = {
  readonly resume: PendingFinalizationResumeView
  readonly blockedCode: string | null
  readonly sync: SyncStateView | null
}

// The administration view models.

export type RecoveryMediumRequestView = {
  readonly runId: string
  readonly requestId: string
  readonly mediumIdHash: string
  readonly index: number
  readonly total: number
  readonly roleCode: string
  readonly certificateHash: string
  readonly expectedThumbprint: string
  readonly protectionCode: number
  readonly testKindCode: string
}

export type RecoveryMediumObservationView = {
  readonly request: RecoveryMediumRequestView
  readonly resultCode: number
  readonly observedThumbprint: string | null
  readonly errorCode: string | null
}

export type RecoveryReportView = {
  readonly completed: boolean
  readonly exactPublicReportJson: string
  readonly envelopeHash: string
  readonly sourceEnvelopeHash: string
  readonly auditId: string
  readonly finishedAtMs: number
  readonly nextDueAtMs: number | null
}

export type RecoveryRunView = {
  readonly operationId: string
  readonly phaseCode: number
  readonly request: RecoveryMediumRequestView | null
  readonly observations: readonly RecoveryMediumObservationView[]
  readonly report: RecoveryReportView | null
  readonly errorCode: string | null
}

export type RecoveryAdministrationView = {
  readonly lastSuccess: RecoveryReportView | null
  readonly lastFailure: RecoveryReportView | null
  readonly run: RecoveryRunView | null
}

export type DestructionTargetView = {
  readonly entryHash: string
  readonly chainSequence: number
  readonly stubObjectHash: string | null
}

export type DestructionPreflightView = {
  readonly jobHash: string
  readonly exactCanonicalReportJson: string
  readonly knownReplicaCount: number
}

export type DestructionReplicaView = {
  readonly deviceId: string
  readonly kindCode: number
  readonly attestationHash: string | null
  readonly resultCode: number | null
  readonly backupExpiryAt: number | null
}

export type DestructionProcessView = {
  readonly destructionId: string
  readonly authorizationObjectHash: string
  readonly state: DestructionStateV1
  readonly scopeCode: number
  readonly legalReasonCode: number
  readonly controllerDeviceId: string
  readonly custodianDeviceId: string
  readonly approverCertificateHashes: readonly string[]
  readonly targets: readonly DestructionTargetView[]
  readonly preflight: DestructionPreflightView | null
  readonly replicas: readonly DestructionReplicaView[]
  readonly evidenceEntryHash: string | null
}

export type DestructionAdministrationView = {
  readonly privacyDecisionEnabled: boolean
  readonly policyHash: string
  readonly knownDestructionIds: readonly string[]
  readonly process: DestructionProcessView | null
}

export type DestructionReaderDeliveryView = {
  readonly destructionId: string
  readonly jobHash: string
  readonly readerId: string
  readonly exactAuthorization: readonly number[]
  readonly exactInitiatingEvent: readonly number[]
  readonly exactJobUpload: readonly number[]
}

export type DestructionEvidenceReviewView = {
  readonly writerDeviceId: string
  readonly process: DestructionProcessView
  readonly preview: FinalizationPreviewView
}

export type PendingDeviceRequestView = {
  readonly requestId: string
  readonly certificateKindCode: string
  readonly fingerprint: string
  readonly receivedAtMs: number
  readonly fingerprintSubject: FingerprintSubjectV1
}

export type TrustCeremonyView = {
  readonly ceremonyId: string
  readonly kind: TrustCeremonyKind
  readonly step: TrustCeremonyStep
  readonly targetFingerprint: string | null
  readonly exchangeFileName: string | null
  readonly round: TrustCeremonyRoundV1
  readonly linkedCeremonyId: string | null
  readonly fingerprintSubject: FingerprintSubjectV1 | null
}

export type PolicyProfileView = {
  readonly operatingProfile: number
  readonly maxRegistryAgeMs: number
  readonly maxFutureClockSkewMs: number
  readonly registryExpiryBehavior: number
  readonly evidenceMaxDelayMs: number
  readonly readerInactivityMs: number
  readonly readerTrustRefreshMs: number
  readonly readerHistoryAccessAllowed: boolean
  readonly backupFrequencyMs: number
  readonly restoreTestIntervalMs: number
  readonly minimumRetentionMs: number | null
  readonly destructionEnabled: boolean
  readonly effectiveFromSequence: number
  readonly leaseValidThroughSequence: number
  readonly notAfterMs: number
}

export type RegistryHealthView = {
  readonly registryVersion: number
  readonly headHash: string
  readonly registryAgeMs: number
  readonly maxRegistryAgeMs: number
  readonly leaseValidThroughSequence: number
  readonly nextSequence: number
  readonly notAfterMs: number
  readonly staleDecision: StaleDecision
}

export type GoLiveRequirementView = {
  readonly requirementCode: string
  readonly status: GoLiveRequirementStatus
  readonly evidenceCode: string
}

export type GoLiveChecklistView = {
  readonly requirements: readonly GoLiveRequirementView[]
  readonly productionReady: boolean
}

export type ClockReleaseOfferView = {
  readonly availability: ClockReleaseAvailability
  readonly floorMs: number | null
  readonly observedWallClockMs: number | null
  readonly maxFutureClockSkewMs: number | null
  readonly expiresAtMs: number | null
  readonly justifications: readonly ClockReleaseJustificationV1[]
}

export type ClockReleaseOutcomeView = {
  readonly releaseId: string
  readonly expiresAtMs: number
  readonly changesTimeFloor: boolean
  readonly changesRegistryExpiry: boolean
  readonly changesLease: boolean
}

export type WriterTransitionView = {
  readonly phase: WriterTransitionPhase
  readonly ceremonyId: string | null
  readonly currentWriterHash: string
  readonly newWriterHash: string | null
  readonly effectiveFromSequence: number | null
}

export type RevocationEffectView = {
  readonly targetClass: RevocationTargetClass
  readonly targetHash: string
  readonly stopsNewGrantsFromSequence: number
  readonly recallsIssuedGrants: boolean
  readonly recallsDecryptedPlaintext: boolean
}

// The value arrays, so that no consumer repeats a literal.

export const SYNC_STATUS_VALUES = [
  'lokal gesichert',
  'Upload ausstehend',
  'synchronisiert',
  'Fehler',
] as const

export const DETAIL_CAUSE_VALUES = [
  'Netzarchiv wartet',
  'Queuegrenze erreicht',
  'Profil nicht freigegeben',
  'Wiederaufnahme erschoepft',
] as const

export const QUARANTINE_REASON_VALUES = [
  'malformed',
  'duplicate',
  'conflicting',
  'unattributable',
] as const

export const LOCAL_AUDIT_OUTCOME_V1_VALUES = [
  'Failed',
  'Accepted',
  'Completed',
] as const

export const KEY_PROTECTION_PROFILE_V1_VALUES = [
  'OsWrapped',
  'HardwareNonExportable',
  'OfflineEncryptedContainer',
  'Pkcs11',
  'ServerSecretStoreOrHsm',
] as const

export const OPERATOR_ROLE_V1_VALUES = [
  'Writer',
  'Reader',
  'OrganizationAdmin',
] as const

export const SIGNER_ROLE_VALUES = [
  'Writer',
  'Reader',
  'OrganizationAdmin',
  'Root',
  'KeyApprover',
  'HistoricalGrantAuthority',
  'ServerReceipt',
  'DeletionAttest',
  'RecoveryRecipient',
] as const

export const FINALIZATION_PHASE_VALUES = [
  'ReversibleDraft',
  'PreparedAndFlushed',
  'DraftKeyAbsent',
  'GrantsPublished',
  'EntryCommitted',
  'NetworkArchivePublished',
  'Reconciled',
] as const

export const STALE_DECISION_VALUES = [
  'Fresh',
  'StaleAcknowledgeable',
  'HardBlock',
] as const

export const HEALTH_FINDING_VALUES = [
  'EA-ARCHIVE-HEALTH-MISSING-FILE',
  'EA-ARCHIVE-HEALTH-MODIFIED-FILE',
  'EA-ARCHIVE-HEALTH-HASH-SIGNATURE-CHAIN',
  'EA-ARCHIVE-HEALTH-MISSING-GRANT',
  'EA-ARCHIVE-HEALTH-UNAUTHORIZED-STUB',
  'EA-ARCHIVE-HEALTH-INCOMPLETE-TRUST',
  'EA-ARCHIVE-HEALTH-ORPHAN-OR-TEMPORARY',
  'EA-ARCHIVE-HEALTH-SEQUENCE-FORK-ROLLBACK',
  'EA-ARCHIVE-HEALTH-FREE-SPACE',
  'EA-ARCHIVE-HEALTH-FILESYSTEM-SEMANTICS',
] as const

export const PATIENT_COUNT_STATUS_VALUES = [
  'Unknown',
  'Known',
] as const

export const LOCAL_WRITER_LOCK_DIAGNOSIS_VALUES = [
  'Missing',
  'AbandonedInert',
  'LiveOwner',
  'Unreadable',
] as const

export const DESTRUCTION_STATE_V1_VALUES = [
  'requested',
  'inProgress',
  'pendingBackupExpiry',
  'completeManagedScope',
  'incompleteUnreachableReplica',
] as const

export const GO_LIVE_REQUIREMENT_STATUS_VALUES = [
  'Confirmed',
  'NotMet',
  'NotAutomaticallyVerifiable',
] as const

export const TRUST_CEREMONY_KIND_VALUES = [
  'DeviceApprove',
  'DeviceRevoke',
  'PolicyChange',
  'WriterTransition',
] as const

export const TRUST_CEREMONY_STEP_VALUES = [
  'PendingRequest',
  'FingerprintConfirmed',
  'AdminAuthorized',
  'RootRequestExported',
  'RootReplyImported',
  'RegistryPublished',
  'TargetPublished',
] as const

export const FINGERPRINT_SUBJECT_V1_VALUES = [
  'RegistrationRequest',
  'IssuedCertificate',
] as const

export const TRUST_CEREMONY_ROUND_V1_VALUES = [
  'IssueTarget',
  'ActivateRegistry',
] as const

export const WRITER_TRANSITION_PHASE_VALUES = [
  'NoTransition',
  'Prepared',
  'Activated',
] as const

export const CLOCK_RELEASE_AVAILABILITY_VALUES = [
  'Offered',
  'IndependentTimeUnavailable',
  'NotBlocked',
] as const

export const REVOCATION_TARGET_CLASS_VALUES = [
  'NonAdminDevice',
  'OperatorBinding',
  'Component',
] as const

export const CLOCK_RELEASE_JUSTIFICATION_V1_VALUES = [
  'OperatorVerifiedWallClock',
  'PlatformTimeSourceRecovery',
  'HardwareClockMaintenance',
] as const
