[package]
name = "einsatzarchiv-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
aws-sdk-s3.workspace = true
aws-smithy-http-client.workspace = true
axum.workspace = true
ea-crypto.workspace = true
ea-format.workspace = true
ea-sync-protocol.workspace = true
ea-sync-server.workspace = true
ea-time.workspace = true
ea-trust.workspace = true
ea-types.workspace = true
hex.workspace = true
rustls.workspace = true
sqlx.workspace = true
sqlx-core.workspace = true
sqlx-postgres.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true

[dev-dependencies]
ea-testkit.workspace = true
sha2.workspace = true
