//! Der Emitter: EINE Zeichenkette, deterministisch, nur Deklarationen.
//!
//! Vier Quellen eines Byteunterschieds zwischen zwei Laeufen sind bekannt, und
//! keine davon existiert hier: die Reihenfolge kommt aus deklarierten Listen
//! und niemals aus einer `HashMap`, nichts formatiert einen Zeitstempel,
//! nichts liest einen Pfad und nichts liest eine Version aus der Umgebung.
//!
//! Die Ausgabe ist **deklarationsfrei von Berechnung**: ein fester
//! Kopfkommentar, `export type`-Vereinigungen, `export type`-Objekttypen und
//! `export const … as const`-Arrays. Keine Funktion, kein Pfeil, keine Klasse,
//! kein Import. `\n` als Zeilenende, zwei Leerzeichen Einrueckung, eine
//! abschliessende Zeilenschaltung.

/// Der Kopf. Er nennt das erzeugende Kommando, damit niemand raten muss, wie
/// die Datei neu entsteht.
const HEADER: &str = "\
// GENERATED — do not edit this file by hand.
// Written by `cargo run --locked -p ea-ui-contracts --bin emit-ts`.
// Every literal below has exactly one source, and that source is Rust.
";

/// Die Ansichtsmodelle in EMITTERREIHENFOLGE, je mit ihren Feldern in
/// Deklarationsreihenfolge.
///
/// Diese Liste ist das TypeScript-Gegenstueck der Rust-Strukturen in
/// `lib.rs`. Sie steht bewusst als Liste und nicht als Ableitung: ohne
/// Ableitungsmakro gibt es in Rust keine Feldreflexion, und ein Makro waere
/// eine zweite Sprache im Kontrakt. Wer ein Feld einer Ansichtsstruktur
/// aendert, aendert dieselbe Zeile hier — und die Driftschranke ueber der
/// eingecheckten Datei macht sichtbar, dass er es getan hat.
/// Die Ansichtsmodelle der READER-Flaeche, in Emitterreihenfolge.
///
/// Getrennt von [`VIEW_MODELS_V1`], weil die zwei Dateien zwei Flaechen
/// bedienen: ein Eintrag hier erscheint in `apps/web`, einer dort in
/// `apps/desktop`, und `no-hand-written-contracts.test.ts` verbannt die
/// Literale jeweils NUR aus seiner eigenen Haelfte.
///
/// # Warum `BundleActivationView` keine zweite geschlossene Union traegt
///
/// Die Entscheidung koennte als `'Activate' | 'KeepActive'` stehen. Dann aber
/// verbannte `no-hand-written-contracts.test.ts` genau diese zwei Literale aus
/// jeder handgeschriebenen Web-Quelle — und der Service Worker, der auf die
/// Entscheidung verzweigen MUSS, koennte sie nicht mehr nennen, ohne ein
/// Werte-Array zu importieren, das es fuer eine Zweiwertmenge nicht braucht.
/// `activated` ist ein `boolean` und traegt denselben Unterschied ohne diesen
/// Preis; der GRUND steht daneben und bleibt eine geschlossene Union, weil er
/// sieben Werte hat und jeder einzelne benannt gehoert.
const READER_VIEW_MODELS_V1: &[(&str, &[(&str, &str)])] = &[
    (
        "BundleActivationView",
        &[
            ("activated", "boolean"),
            // Nur gesetzt, wenn aktiviert wurde: der Cache wird unter dieser
            // Fassung gefuehrt.
            ("bundleVersion", "string | null"),
            // Nur gesetzt, wenn NICHT aktiviert wurde.
            ("rejectionCode", "BundleRejectionCodeV1 | null"),
        ],
    ),
    (
        // Das Ergebnis EINES Oeffnens im Datei-Modus, und ausdruecklich keine
        // Zeile je Eintrag: die zeilenweise Darstellung gehoert der
        // Reader-Oberflaeche, diese Flaeche zeigt einen Bestand.
        //
        // Es traegt KEINE Modus-Vereinigung. Eine Union `'server' | 'file'`
        // verbaenne ihre zwei Literale aus jeder handgeschriebenen Web-Quelle
        // — und `<input type="file">` in `OpenArchivePanel.tsx` ist genau
        // `"file"`. Dieselbe Ueberlegung wie bei `BundleActivationView` oben,
        // dort zugunsten eines `boolean` entschieden; hier braucht es gar
        // nichts: die Route sagt, wo man ist, und `OpenedArchiveV1::mode()`
        // bleibt ein reiner Rust-Begriff.
        "FileModeArchiveView",
        &[
            ("archiveObjectCount", "number"),
            ("entryPackageCount", "number"),
            ("fullyVerified", "boolean"),
            ("gapCount", "number"),
            ("serverConfirmedCount", "number"),
            ("notServerConfirmedCount", "number"),
            // Der ARCHIVWEITE Wert, gefaltet in Rust: `server-bestätigt` nur,
            // wenn es mindestens ein Objektergebnis gibt UND jedes einzelne
            // ihn traegt. Die Flaeche bekommt den Wortlaut damit aus
            // `ServerConfirmationV1::label` und schreibt ihn nie selbst — sie
            // DARF ihn nach `no-hand-written-contracts.test.ts` auch gar nicht
            // schreiben.
            ("serverConfirmation", "ServerConfirmationV1"),
        ],
    ),
    (
        // Dieselben drei Feldnamen wie in `FinalizationPreviewView`: es ist
        // dieselbe Policy-Rechnung, nur auf der anderen Flaeche, und zwei
        // Namen fuer dieselbe Groesse waeren die Drift, gegen die es diese
        // Crate gibt.
        "ReaderTrustAgeView",
        &[
            ("trustAgeMs", "number"),
            ("readerTrustRefreshMs", "number"),
            ("trustRefreshOverdue", "boolean"),
        ],
    ),
    // ------------------------------------------------------------------
    // Die Reader-Ansichten der Aufgabe „Integritätszentrierte
    // Reader-Oberfläche". Die Felder folgen `design.md` §17.2 — und dem, was
    // der Arbeitsbaum ERZEUGEN kann. Drei Felder der Vorfassung haben keinen
    // Erzeuger und stehen deshalb nicht im Vertrag: `writerKeyThumbprint`
    // (das Manifest traegt `writer_certificate_hash`, und der ist der
    // „Writer-Key" der technischen Ansicht), `evidence: EvidenceStatus`
    // (`ea-verify` konstruiert `EvidenceStatus` nirgends; ein `vollstaendig`
    // ohne Erzeuger waere der Ueberanspruch, den §17.4 verbietet) und
    // `occurredAtLocal` (der einzige Ortszeit-Formatierer in `ea-schema` ist
    // privat; die Bruecke gibt UTC-Millisekunden und die IANA-Zeitzone
    // heraus, die Darstellung formatiert mit `Intl.DateTimeFormat`).
    // ------------------------------------------------------------------
    (
        // Der TECHNISCHE Zustand eines Eintrags — er existiert auch dann,
        // wenn nichts entschluesselt wurde. Die drei Dimensionen stehen
        // NEBENEINANDER; eine zusammengefaltete waere §17.4 zuwider.
        "ReaderEntryStateView",
        &[
            ("entryHash", "string"),
            ("objectHash", "string"),
            ("sequence", "number"),
            ("verification", "VerificationStatus"),
            ("entryState", "EntryStatus"),
            ("serverConfirmation", "ServerConfirmationV1"),
            ("detailCode", "string | null"),
        ],
    ),
    (
        // Der FACHLICHE Inhalt — und der entsteht ausschliesslich aus einem
        // entschluesselten Datensatz. `null` ist hier kein leerer Einsatz,
        // sondern die Aussage, dass nicht entschluesselt wurde.
        "ReaderIncidentView",
        &[
            ("incidentNumber", "string"),
            ("occurredAtStartMs", "number"),
            ("timezone", "string"),
            ("keyword", "string"),
        ],
    ),
    (
        "ReaderEntryView",
        &[
            ("state", "ReaderEntryStateView"),
            ("incident", "ReaderIncidentView | null"),
        ],
    ),
    (
        // Die technische Ansicht aus §17.2, Feld fuer Feld aus Manifest und
        // Bericht: Sequenz, Hashes, Writer-Zertifikat, Registry, Receipt,
        // Evidence.
        "ReaderTechnicalView",
        &[
            ("sequence", "number"),
            ("previousEntryHash", "string | null"),
            ("entryHash", "string"),
            ("ciphertextHash", "string"),
            ("writerCertificateHash", "string"),
            ("registryVersion", "number"),
            ("registryHeadHash", "string"),
            ("serverConfirmation", "ServerConfirmationV1"),
            ("evidenceDetailCode", "string | null"),
        ],
    ),
    (
        // Ein Knoten der Integritaetsleiste. Er entsteht nur fuer ein Tor,
        // ueber das der Bericht eine Aussage TRAGEN kann; `null` ist „nicht
        // geprueft" — der Baustein bleibt dreiwertig, und ein `boolean`
        // koennte den dritten Wert nicht tragen.
        "ChainIntegrityNodeView",
        &[
            ("label", "string"),
            ("verified", "boolean | null"),
            ("detail", "string | null"),
        ],
    ),
    (
        "VerificationProblemView",
        &[
            ("objectHash", "string"),
            ("verification", "VerificationStatus"),
            ("detailCode", "string | null"),
        ],
    ),
    (
        // Der geoeffnete Bestand als Ganzes: die Liste, die `ReaderPage`
        // rendert.
        "ReaderStandView",
        &[
            ("entries", "readonly ReaderEntryView[]"),
            ("problems", "readonly VerificationProblemView[]"),
            ("chain", "readonly ChainIntegrityNodeView[]"),
            ("fullyVerified", "boolean"),
            ("serverConfirmation", "ServerConfirmationV1"),
        ],
    ),
    (
        // Original und Nachtraege als GETRENNTE Ansichten desselben
        // Zusammenhangs; nichts ist zusammengefuehrt, nichts ueberholt.
        "ReaderRejectedAmendmentView",
        &[
            ("entryHash", "string"),
            ("sequence", "number"),
            ("reason", "string"),
        ],
    ),
    (
        "ReaderAmendmentThreadView",
        &[
            ("original", "ReaderEntryView"),
            ("amendments", "readonly ReaderEntryView[]"),
            ("rejected", "readonly ReaderRejectedAmendmentView[]"),
        ],
    ),
    (
        "ReaderSearchHitView",
        &[
            ("entryHash", "string"),
            ("sequence", "number"),
            ("incidentNumber", "string"),
            ("occurredAtStartMs", "number"),
        ],
    ),
];

const VIEW_MODELS_V1: &[(&str, &[(&str, &str)])] = &[
    (
        "SyncStateView",
        &[
            ("status", "SyncStatus"),
            ("detailCause", "DetailCause | null"),
        ],
    ),
    (
        "FinalizationPreviewView",
        &[
            ("proposedSequence", "number"),
            ("bindsPredecessor", "boolean"),
            ("effectiveNow", "number"),
            ("trustAgeMs", "number"),
            ("readerTrustRefreshMs", "number"),
            ("trustRefreshOverdue", "boolean"),
            ("staleDecision", "StaleDecision"),
        ],
    ),
    (
        // Hashes UND Sequenz: nach dem Commit ist das alles, was die
        // Oberflaeche ueber den Eintrag erfaehrt — und mehr als die Sequenz
        // allein, weil ein Fingerabdruck ohne Hash keiner ist.
        "FinalizeOutcomeView",
        &[
            ("sequence", "number"),
            ("entryHash", "string"),
            ("objectHash", "string"),
            ("sync", "SyncStateView"),
        ],
    ),
    (
        "ArchiveHealthSummaryView",
        &[
            ("healthy", "boolean"),
            ("findingCodes", "readonly HealthFinding[]"),
            ("quarantineReasons", "readonly QuarantineReason[]"),
        ],
    ),
    (
        "PostureRequirementView",
        &[
            ("requirementCode", "string"),
            ("satisfied", "boolean | null"),
            ("evidenceCode", "string"),
        ],
    ),
    (
        "DevicePostureSummaryView",
        &[
            ("requirements", "readonly PostureRequirementView[]"),
            ("productionReady", "boolean"),
        ],
    ),
    (
        "PendingFinalizationResumeView",
        &[
            ("phase", "FinalizationPhase"),
            ("irreversible", "boolean"),
            ("outcomeCode", "string | null"),
            ("outcomeSequence", "number | null"),
        ],
    ),
    (
        "IncidentIdentityView",
        &[("localCivilYear", "number"), ("incidentNumber", "string")],
    ),
    (
        "CoordinatesView",
        &[("latE7", "number"), ("lonE7", "number")],
    ),
    (
        "OccurredAtView",
        &[("start", "number"), ("end", "number | null")],
    ),
    (
        "KeywordView",
        &[("referenceId", "string | null"), ("displayText", "string")],
    ),
    (
        "StructuredAddressView",
        &[
            ("street", "string | null"),
            ("houseNumber", "string | null"),
            ("postalCode", "string | null"),
            ("locality", "string | null"),
            ("adminArea", "string | null"),
            ("countryCode", "string | null"),
        ],
    ),
    (
        "LocationView",
        &[
            ("freeText", "string | null"),
            ("address", "StructuredAddressView | null"),
            ("coordinates", "CoordinatesView | null"),
        ],
    ),
    (
        "PersonnelSelectionView",
        &[
            ("masterPersonnelId", "string | null"),
            ("displayName", "string"),
            ("roleLabel", "string | null"),
        ],
    ),
    (
        "VehicleSelectionView",
        &[
            ("masterVehicleId", "string | null"),
            ("displayName", "string"),
            ("radioCallName", "string | null"),
            ("licensePlate", "string | null"),
        ],
    ),
    (
        "ExternalOrganizationView",
        &[("id", "string | null"), ("displayName", "string")],
    ),
    (
        "IncidentInputView",
        &[
            ("humanIncidentNumber", "string"),
            ("occurredAt", "OccurredAtView"),
            ("keyword", "KeywordView"),
            ("location", "LocationView"),
            ("personnel", "readonly PersonnelSelectionView[]"),
            ("personnelEmptyReason", "string | null"),
            ("vehicles", "readonly VehicleSelectionView[]"),
            ("vehiclesEmptyReason", "string | null"),
            // ZWEI Positionen, obwohl `IncidentInputView` in Rust EINEN Wert
            // fuehrt (`PatientCountView`). Das ist Absicht und keine Drift:
            // die Drahtform ist `payload-wire-addendum.md`:102-118 mit
            // `patientCountStatus` und `patientCount` als getrennte Positionen,
            // und die Grenze faltet sie fail-closed zusammen, damit Anzeige und
            // Draht danach nicht mehr auseinanderlaufen koennen.
            ("patientCountStatus", "PatientCountStatus"),
            ("patientCount", "number | null"),
            ("notes", "string | null"),
            (
                "externalOrganizations",
                "readonly ExternalOrganizationView[]",
            ),
        ],
    ),
    (
        "DraftStateView",
        &[("incident", "IncidentInputView"), ("sync", "SyncStateView")],
    ),
    (
        "MasterDataResultView",
        &[
            ("personnel", "readonly PersonnelSelectionView[]"),
            ("vehicles", "readonly VehicleSelectionView[]"),
            ("personnelTotal", "number"),
            ("vehicleTotal", "number"),
        ],
    ),
    (
        "StaleAcknowledgementView",
        &[("captured", "boolean"), ("proofCode", "string")],
    ),
    (
        "ReauthResultView",
        &[("fresh", "boolean"), ("purposeCode", "string")],
    ),
    (
        "DiscardStateView",
        &[("phaseCode", "string"), ("complete", "boolean")],
    ),
    (
        "BundleExportView",
        &[
            ("path", "string"),
            ("objectCount", "number"),
            ("byteCount", "number"),
        ],
    ),
    (
        "PendingResumeOutcomeView",
        &[
            ("resume", "PendingFinalizationResumeView"),
            ("blockedCode", "string | null"),
            ("sync", "SyncStateView | null"),
        ],
    ),
];

/// Die vollstaendige TypeScript-Kontraktdatei als Zeichenkette.
///
/// Zwei Aufrufe liefern byteidentische Ergebnisse; das ist zugesichert und
/// nicht bloss beobachtet (`tests/generated_ts_is_current.rs`).
#[must_use]
pub fn emit_typescript() -> String {
    let mut emitted = String::from(HEADER);

    emitted.push_str("\n// The closed unions of the contract surface.\n");
    for (name, literals) in closed_unions() {
        push_union(&mut emitted, name, literals);
    }

    emitted.push_str("\n// The Writer view models.\n");
    for (name, fields) in VIEW_MODELS_V1 {
        push_object(&mut emitted, name, fields);
    }

    emitted.push_str("\n// The value arrays, so that no consumer repeats a literal.\n");
    for (name, literals) in closed_unions() {
        push_values(&mut emitted, name, literals);
    }

    emitted
}

/// Die vollstaendige TypeScript-Kontraktdatei des READERS als Zeichenkette.
///
/// Derselbe Kopf, dieselbe Determinismuszusage, dieselben Formregeln — eine
/// ANDERE Menge Vereinigungen. ZWEI Ausdruecke statt einer Datei mit beidem,
/// weil `apps/desktop/src/bridge/no-hand-written-contracts.test.ts` jedes
/// Literal JEDER emittierten Vereinigung aus jeder handgeschriebenen
/// Desktop-Quelle verbannt: `ungueltig`, `vorhanden` oder `ausstehend` dort
/// einzutragen verengte die Writer-Flaeche ohne Reader-Grund.
///
/// Zwei Aufrufe liefern byteidentische Ergebnisse; das ist zugesichert und
/// nicht bloss beobachtet (`tests/generated_ts_is_current.rs`).
#[must_use]
pub fn emit_reader_typescript() -> String {
    let mut emitted = String::from(HEADER);

    emitted.push_str("\n// The closed unions of the contract surface.\n");
    for (name, literals) in crate::READER_ENUMS_V1 {
        push_union(&mut emitted, name, literals);
    }

    emitted.push_str("\n// The view models of the reader surface.\n");
    for (name, fields) in READER_VIEW_MODELS_V1 {
        push_object(&mut emitted, name, fields);
    }

    emitted.push_str("\n// The value arrays, so that no consumer repeats a literal.\n");
    for (name, literals) in crate::READER_ENUMS_V1 {
        push_values(&mut emitted, name, literals);
    }

    emitted
}

/// Jede emittierte Vereinigung, in fester Reihenfolge: erst die
/// Sicherheitsaufzaehlungen, dann die uebrigen geschlossenen Mengen.
fn closed_unions() -> impl Iterator<Item = &'static (&'static str, &'static [&'static str])> {
    crate::SECURITY_ENUMS_V1
        .iter()
        .chain(crate::WRITER_ENUMS_V1)
}

fn push_union(emitted: &mut String, name: &str, literals: &[&str]) {
    emitted.push_str("\nexport type ");
    emitted.push_str(name);
    emitted.push_str(" =\n");
    for literal in literals {
        emitted.push_str("  | '");
        emitted.push_str(literal);
        emitted.push_str("'\n");
    }
}

fn push_object(emitted: &mut String, name: &str, fields: &[(&str, &str)]) {
    emitted.push_str("\nexport type ");
    emitted.push_str(name);
    emitted.push_str(" = {\n");
    for (field, declared_type) in fields {
        emitted.push_str("  readonly ");
        emitted.push_str(field);
        emitted.push_str(": ");
        emitted.push_str(declared_type);
        emitted.push('\n');
    }
    emitted.push_str("}\n");
}

fn push_values(emitted: &mut String, name: &str, literals: &[&str]) {
    emitted.push_str("\nexport const ");
    emitted.push_str(&screaming_snake(name));
    emitted.push_str("_VALUES = [\n");
    for literal in literals {
        emitted.push_str("  '");
        emitted.push_str(literal);
        emitted.push_str("',\n");
    }
    emitted.push_str("] as const\n");
}

/// `LocalAuditOutcomeV1` wird zu `LOCAL_AUDIT_OUTCOME_V1`.
fn screaming_snake(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    let mut previous_is_lower_or_digit = false;
    for character in name.chars() {
        if character.is_ascii_uppercase() && previous_is_lower_or_digit {
            out.push('_');
        }
        previous_is_lower_or_digit = character.is_ascii_lowercase() || character.is_ascii_digit();
        out.push(character.to_ascii_uppercase());
    }
    out
}
