[package]
name = "ea-sync-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
aws-sdk-s3.workspace = true
ea-crypto.workspace = true
ea-format.workspace = true
ea-sync-protocol.workspace = true
ea-types.workspace = true
hex.workspace = true
