// GENERATED — do not edit this file by hand.
// Written by `cargo run --locked -p ea-ui-contracts --bin emit-ts`.
// Every literal below has exactly one source, and that source is Rust.

// The closed unions of the contract surface.

export type VerificationStatus =
  | 'verifiziert'
  | 'Lücke'
  | 'fehlender Grant'
  | 'unbekannter Schlüssel'
  | 'nicht darstellbares Schema'
  | 'ungültig'

export type EntryStatus =
  | 'vorhanden'
  | 'autorisiert vernichtet'
  | 'ungeklärte Lücke'

export type EvidenceStatus =
  | 'vollständig'
  | 'ausstehend'
  | 'überfällig'
  | 'ungültig'

export type ServerConfirmationV1 =
  | 'server-bestätigt'
  | 'nicht server-bestätigt'

export type BundleRejectionCodeV1 =
  | 'NoPinnedRelease'
  | 'Unsigned'
  | 'WrongRoot'
  | 'WrongOrganization'
  | 'Revoked'
  | 'NotYetEffective'
  | 'HashMismatch'

// The view models of the reader surface.

export type BundleActivationView = {
  readonly activated: boolean
  readonly bundleVersion: string | null
  readonly rejectionCode: BundleRejectionCodeV1 | null
}

export type FileModeArchiveView = {
  readonly archiveObjectCount: number
  readonly entryPackageCount: number
  readonly fullyVerified: boolean
  readonly gapCount: number
  readonly serverConfirmedCount: number
  readonly notServerConfirmedCount: number
  readonly serverConfirmation: ServerConfirmationV1
}

export type ReaderTrustAgeView = {
  readonly trustAgeMs: number
  readonly readerTrustRefreshMs: number
  readonly trustRefreshOverdue: boolean
}

// The value arrays, so that no consumer repeats a literal.

export const VERIFICATION_STATUS_VALUES = [
  'verifiziert',
  'Lücke',
  'fehlender Grant',
  'unbekannter Schlüssel',
  'nicht darstellbares Schema',
  'ungültig',
] as const

export const ENTRY_STATUS_VALUES = [
  'vorhanden',
  'autorisiert vernichtet',
  'ungeklärte Lücke',
] as const

export const EVIDENCE_STATUS_VALUES = [
  'vollständig',
  'ausstehend',
  'überfällig',
  'ungültig',
] as const

export const SERVER_CONFIRMATION_V1_VALUES = [
  'server-bestätigt',
  'nicht server-bestätigt',
] as const

export const BUNDLE_REJECTION_CODE_V1_VALUES = [
  'NoPinnedRelease',
  'Unsigned',
  'WrongRoot',
  'WrongOrganization',
  'Revoked',
  'NotYetEffective',
  'HashMismatch',
] as const
